<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Zucchi\Module'                                  => __DIR__ . '//Module.php',
    'Zucchi\Event\EventProviderTrait'                => __DIR__ . '//src/Zucchi/Event/EventProviderTrait.php',
    'Zucchi\DateTime\Time'                           => __DIR__ . '//src/Zucchi/DateTime/Time.php',
    'Zucchi\DateTime\DateTime'                       => __DIR__ . '//src/Zucchi/DateTime/DateTime.php',
    'Zucchi\DateTime\Date'                           => __DIR__ . '//src/Zucchi/DateTime/Date.php',
    'Zucchi\Controller\Plugin\Messenger'             => __DIR__ . '//src/Zucchi/Controller/Plugin/Messenger.php',
    'Zucchi\Controller\AbstractRestController'       => __DIR__ . '//src/Zucchi/Controller/AbstractRestController.php',
    'Zucchi\Debug\Debug'                             => __DIR__ . '//src/Zucchi/Debug/Debug.php',
    'Zucchi\Filter\Cast\Boolean'                     => __DIR__ . '//src/Zucchi/Filter/Cast/Boolean.php',
    'Zucchi\Filter\Cast\Integer'                     => __DIR__ . '//src/Zucchi/Filter/Cast/Integer.php',
    'Zucchi\View\Helper\Filter'                      => __DIR__ . '//src/Zucchi/View/Helper/Filter.php',
    'Zucchi\View\Helper\Truncate'                    => __DIR__ . '//src/Zucchi/View/Helper/Truncate.php',
    'Zucchi\ServiceManager\ServiceManagerAwareTrait' => __DIR__ . '//src/Zucchi/ServiceManager/ServiceManagerAwareTrait.php',
);